import Vue from 'vue'

/**
 * This object defines the programming languages supported for code highlighting
 * using CodeMirror
 * @namespace cmMode The programminglanguages supported
 */
const mimeTypesForLanguage = {
    'c': 'text/x-csrc', // (C),
    'c++': 'text/x-c++src', // (C++),
    'c#': 'text/x-csharp', // (C#),
    'css': 'text/css', // (CSS)
    'fortran': 'text/x-fortran', // (Fortran)
    'glsl': 'text/x-glsl', // (GLSL)
    'html': 'text/html', // (HTML)
    'java': 'text/x-java', // (Java),
    'javascript': 'text/javascript', // (JavaScript)
    'objectivec': 'text/x-objectivec', // (Objective-C),
    'perl': 'text/x-perl', // (Perl)
    'php': 'application/x-httpd-php', // (PHP)
    'python': 'text/x-python', // (Python)
    'r': 'text/x-rsrc', //(R)
    'ruby': 'text/x-ruby', // (Ruby)
    'sql': 'text/x-mysql', // (mysql)
    'xml': 'application/xml' //text/html (XML)
};


function loadSettings(scope){
    let options = {
        baseurl : ''
    }
    const settings = scope.querySelectorAll("meta[name^=codeblocks]");
    settings.forEach(opt => {
        const name = opt.getAttribute('name');
        const value = opt.getAttribute('content');
        
        if (name=='codeblocks-baseurl'){
            options.baseurl = value;
        }
    })
    return options;
}


Vue.prototype.$CodeBlock = {
  format_info:function(text){
    return '<span style="color:green">'+text+'</span>';
  },
  format_error:function(text){
    return '<span style="color:red">'+text+'</span>';
  },
  /**
   * Seperates an outputObject (like the one you will get in the update-method of a playground handler) into a string and a json object seperated by a magic String. Returns an object that contains 
   *  <code>type</code> = <code>'dual'</code> parsed a magic string, <code>'json'</code> parsed as json, <code>'text'</code> plain text
   *  <code>json</code> = the JSON object that was sent after the magicString
   *  <code>text</code> = the String that was sent before the magicString
   * @param {*} outputObject  The outputObject generated by the student code
   * @param {*} autoJSON  When true, output that starts with [ or { will be parsed as JSON
   * @param {*} magicString The seperating String. By default it is '\n\n<JSON>\n'
   */
  processMixedOutput(outputObject, autoJSON, magicString) {
      if (magicString===undefined) magicString = '\n\n<JSON>\n';
      const idx = outputObject.indexOf(magicString);    
      if (idx >= 0) {
          const str = outputObject.substr(0, idx);
          const json = JSON.parse(outputObject.substr(idx+magicString.length)); 
      
          return {
              type:'dual',
              json:json,
              text:str
          };
      } else if (outputObject.indexOf('[')!=-1 || outputObject.indexOf('{')!=-1) {
          return {
              type:'json',
              json:JSON.parse(outputObject),
              text:""
          };
      }

      return {
          type:'text',
          json:undefined,
          text:outputObject
      };
  },
  mimeType(language){
      return mimeTypesForLanguage[language];
  },
  ...loadSettings(document)
}

Vue.$CodeBlock = Vue.prototype.$CodeBlock